name: MSFT java app for github actions 1
on: push
jobs:
    First-job:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              name: Cloning the git repo
            - run: npm install
              name: Installing the dependencies
            - run: npm run build
              name: Building the project
            - uses: actions/upload-artifact@v4
              name: upload the artifact
              with:
                name: static-site
                path : .next/

            
